-- MySQL Script generated by MySQL Workbench
-- 07/29/19 19:50:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema photoAppDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photoAppDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photoAppDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `photoAppDB` ;

-- -----------------------------------------------------
-- Table `photoAppDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoAppDB`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tagName` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoAppDB`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT(200) NOT NULL,
  `cameraSpecs` TEXT(200) NOT NULL,
  `captureDate` DATETIME NOT NULL,
  `thumbnailPath` VARCHAR(255) NOT NULL,
  `userId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `fk_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `photoAppDB`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoAppDB`.`tier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`tier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(8,2) NOT NULL,
  `patWithWatermark` VARCHAR(255) NOT NULL,
  `pathWithoutWatermark` VARCHAR(255) NOT NULL,
  `size` ENUM('L','M','S') NOT NULL,
  `productId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productId_idx` (`productId` ASC),
  CONSTRAINT `fk_productId`
    FOREIGN KEY (`productId`)
    REFERENCES `photoAppDB`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoAppDB`.`orderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`orderItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `tierId` INT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_userId_ord_idx` (`userId` ASC),
  INDEX `fk_tierId_idx` (`tierId` ASC),
  CONSTRAINT `fk_userId_ord`
    FOREIGN KEY (`userId`)
    REFERENCES `photoAppDB`.`user` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tierId`
    FOREIGN KEY (`tierId`)
    REFERENCES `photoAppDB`.`tier` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photoAppDB`.`product_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photoAppDB`.`product_tag` (
  `id` INT NOT NULL,
  `productId` INT NULL,
  `tagId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productId_tag_idx` (`productId` ASC),
  INDEX `fk_tagId_idx` (`tagId` ASC),
  CONSTRAINT `fk_productId_tag`
    FOREIGN KEY (`productId`)
    REFERENCES `photoAppDB`.`product` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tagId`
    FOREIGN KEY (`tagId`)
    REFERENCES `photoAppDB`.`tag` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
